// eslint-disable-next-line import/prefer-default-export, no-shadow
export enum DocumentsActionTypes {
  FETCH_DOCUMENTS = 'FETCH_DOCUMENTS',
  FILTER_SUBCATEGORY = 'FILTER_SUBCATEGORY',
  FILTER_CHILDSUBCATEGORY = 'FILTER_CHILDSUBCATEGORY',
  SET_NAME_PRODUCT = 'SET_NAME_PRODUCT',
  FETCH_SHIPPINGS = 'FETCH_SHIPPINGS',
  ADD_PRODUCT = 'ADD_PRODUCT'
}
