export enum DocumentsMutationTypes {
  SET_DATA = 'SET_DATA',
  SET_SUBCATEGORY = 'SET_SUBCATEGORY',
  SET_CHILDSUBCATEGORY = 'SET_CHILDSUBCATEGORY',
  SET_NAME_PRODUCT = 'SET_NAME_PRODUCT',
  SET_SHIPPINGS = 'SET_SHIPPINGS',
  SET_SHIPPING = 'SET_SHIPPING'
}
